destination: _site/
url: "http://127.0.0.1:4011"
baseurl: "/cbptt-apiref-pdf"
port: 4011
output: pdf
product: cbptt-apiref
print_title: Coinbase Pro Trading Toolkit API reference
print_subtitle: version 0.1
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
